/**
 * 图像工具：统一用 Bing 缩略图生成图片 URL
 * 关键词优先从 searchKeywords[id] 查表，否则根据 name/title 自动生成
 *
 * URL 格式：https://tse1.mm.bing.net/th?q={keyword}&w={width}&h={height}&c=7&p=0
 */

const BASE = 'https://tse1.mm.bing.net/th'

/**
 * 根据关键词和尺寸生成 Bing 缩略图 URL
 */
export function bingImage(keyword: string, w = 800, h = 450): string {
  return `${BASE}?q=${encodeURIComponent(keyword)}&w=${w}&h=${h}&c=7&p=0`
}

/**
 * 人物 id -> 搜索关键词（优先精确）
 * 没填则按 name 退回到通用关键词
 */
export const personSearchKeywords: Record<string, string> = {
  // ===== 中国古代 =====
  'p-qin-shi-huang': '秦始皇 portrait terracotta',
  'p-han-wudi': '汉武帝 portrait',
  'p-tang-taizong': '唐太宗 portrait',
  'p-kangxi': '康熙 emperor portrait',
  'p-qianlong': '乾隆 emperor portrait',
  'p-wu-zetian': '武则天 portrait',
  'p-wen-tianxiang': '文天祥 portrait',
  'p-yue-fei': '岳飞 portrait statue',
  'p-lu-buwei': '吕不韦 portrait',
  'p-shang-yang': '商鞅 portrait',
  'p-han-xin': '韩信 portrait',
  'p-zhang-qian': '张骞 portrait',
  'p-ban-chao': '班超 portrait',
  'p-li-shimin': '李世民 portrait',
  'p-li-bai': '李白 poet portrait',
  'p-du-fu': '杜甫 poet portrait',
  'p-bai-juyi': '白居易 poet portrait',
  'p-su-shi': '苏轼 poet portrait',
  'p-wang-anshi': '王安石 portrait',
  'p-sima-guang': '司马光 portrait',
  'p-sima-qian': '司马迁 portrait',
  'p-sun-tzu': '孙子 portrait',
  'p-zhu-ge-liang': '诸葛亮 portrait',
  'p-zheng-he': '郑和 portrait',
  'p-qu-yuan': '屈原 poet portrait',
  'p-tao-yuanming': '陶渊明 poet portrait',
  'p-wang-wei': '王维 poet portrait',
  'p-li-qingzhao': '李清照 poet portrait',
  'p-luo-binwang': '骆宾王 portrait',
  'p-buddha': '释迦牟尼 buddha statue',
  'p-confucius': '孔子 confucius portrait',
  'p-mencius': '孟子 portrait',
  'p-zhuangzi': '庄子 portrait',
  'p-laozi': '老子 laozi portrait',
  'p-sun-yat-sen': '孙中山 portrait',
  'p-mao-zedong': '毛泽东 portrait',
  'p-chiang-kai-shek': '蒋介石 portrait',
  // ===== 世界古代 =====
  'p-julius-caesar': 'julius caesar bust',
  'p-augustus': 'augustus caesar statue',
  'p-marcus-aurelius': 'marcus aurelius bust',
  'p-alexander': 'alexander the great mosaic',
  'p-cleopatra': 'cleopatra portrait',
  'p-ramses-ii': 'ramesses ii egypt',
  'p-hammurabi': 'hammurabi stele',
  'p-cyrus': 'cyrus the great',
  'p-darius': 'darius the great persepolis',
  'p-xerxes': 'xerxes relief',
  'p-hannibal': 'hannibal barca portrait',
  'p-spartacus': 'spartacus roman',
  'p-leonidas': 'leonidas sparta 300',
  'p-pericles': 'pericles bust',
  'p-socrates': 'socrates bust',
  'p-plato': 'plato bust',
  'p-aristotle': 'aristotle bust',
  'p-archimedes': 'archimedes bust',
  'p-pythagoras': 'pythagoras bust',
  'p-euclid': 'euclid portrait',
  'p-hippocrates': 'hippocrates portrait',
  'p-ptolemy': 'ptolelemy egypt',
  // ===== 中世纪 =====
  'p-constantine': 'constantine the great',
  'p-justinian': 'justinian mosaic',
  'p-charlemagne': 'charlemagne portrait',
  'p-otto': 'otto i holy roman',
  'p-saladin': 'saladin ayyubid',
  'p-richard-lionheart': 'richard the lionheart',
  'p-joan-of-arc': 'joan of arc painting',
  'p-genghis-khan': 'genghis khan portrait',
  'p-kublai-khan': 'kublai khan portrait',
  'p-tamerlane': 'tamerlane timur',
  'p-marco-polo': 'marco polo portrait',
  'p-thomas-aquinas': 'thomas aquinas',
  // ===== 文艺复兴 =====
  'p-leonardo': 'leonardo da vinci self portrait',
  'p-michelangelo': 'michelangelo self portrait',
  'p-raphael': 'raphael self portrait',
  'p-donatello': 'donatello sculptor',
  'p-botticelli': 'botticelli self portrait',
  'p-titian': 'titian self portrait',
  'p-machiavelli': 'niccolo machiavelli portrait',
  'p-lorenzo-de-medici': 'lorenzo de medici',
  'p-columbus': 'christopher columbus portrait',
  'p-vasco-da-gama': 'vasco da gama',
  'p-magellan': 'ferdinand magellan',
  'p-copernicus': 'copernicus portrait',
  'p-galileo': 'galileo portrait',
  'p-vesalius': 'andreas vesalius',
  'p-harvey': 'william harvey portrait',
  'p-newton': 'isaac newton portrait',
  'p-kepler': 'johannes kepler portrait',
  'p-bacon': 'francis bacon portrait',
  'p-descartes': 'rene descartes portrait',
  'p-pascal': 'blaise pascal portrait',
  'p-leibniz': 'gottfried leibniz portrait',
  'p-locke': 'john locke portrait',
  // ===== 启蒙/革命 =====
  'p-louis-xiv': 'louis xiv portrait',
  'p-peter-great': 'peter the great russia',
  'p-frederick-great': 'frederick the great prussia',
  'p-maria-theresa': 'maria theresa',
  'p-catherine-great': 'catherine the great',
  'p-washington': 'george washington portrait',
  'p-jefferson': 'thomas jefferson portrait',
  'p-franklin': 'benjamin franklin portrait',
  'p-hamilton': 'alexander hamilton portrait',
  'p-lafayette': 'lafayette portrait',
  'p-robespierre': 'robespierre portrait',
  'p-napoleon': 'napoleon bonaparte portrait',
  'p-wellington': 'duke of wellington',
  'p-nelson': 'horatio nelson portrait',
  'p-bolivar': 'simon bolivar portrait',
  'p-san-martin': 'jose de san martin',
  'p-montesquieu': 'montesquieu portrait',
  'p-voltaire': 'voltaire portrait',
  'p-rousseau': 'jean jacques rousseau portrait',
  'p-diderot': 'diderot portrait',
  'p-adam-smith': 'adam smith portrait',
  'p-kant': 'immanuel kant portrait',
  'p-hume': 'david hume portrait',
  'p-hegel': 'hegel portrait',
  // ===== 工业革命 =====
  'p-watt': 'james watt steam engine',
  'p-stephenson': 'george stephenson',
  'p-fulton': 'robert fulton portrait',
  'p-edison': 'thomas edison portrait',
  'p-tesla': 'nikola tesla portrait',
  'p-bell': 'alexander graham bell',
  'p-marconi': 'guglielmo marconi',
  'p-ford': 'henry ford portrait',
  'p-rockefeller': 'john d rockefeller',
  'p-carnegie': 'andrew carnegie portrait',
  'p-darwin': 'charles darwin portrait',
  'p-pasteur': 'louis pasteur portrait',
  'p-koch': 'robert koch portrait',
  'p-fleming': 'alexander fleming portrait',
  'p-lister': 'joseph lister surgery',
  'p-mendel': 'gregor mendel portrait',
  // ===== 近代 =====
  'p-marx': 'karl marx portrait',
  'p-engels': 'friedrich engels portrait',
  'p-lenin': 'lenin portrait',
  'p-stalin': 'stalin portrait',
  'p-trotsky': 'leon trotsky portrait',
  'p-hitler': 'adolf hitler portrait',
  'p-mussolini': 'mussolini portrait',
  'p-churchill': 'winston churchill portrait',
  'p-roosevelt': 'fdr roosevelt portrait',
  'p-truman': 'harry truman portrait',
  'p-de-gaulle': 'charles de gaulle',
  'p-gandhi': 'mahatma gandhi portrait',
  'p-nehru': 'nehru portrait',
  'p-mandela': 'nelson mandela portrait',
  'p-einstein': 'albert einstein portrait',
  'p-bohr': 'niels bohr portrait',
  'p-heisenberg': 'heisenberg portrait',
  'p-curie': 'marie curie portrait',
  'p-feynman': 'richard feynman',
  'p-turing': 'alan turing portrait',
  'p-russell': 'bertrand russell portrait',
  'p-sartre': 'jean paul sartre',
  'p-foucault': 'michel foucault',
}

/**
 * 战争 id -> 搜索关键词
 */
export const warSearchKeywords: Record<string, string> = {
  'war-peloponnesian': 'peloponnesian war',
  'war-alexander': 'alexander the great battle',
  'war-punic': 'punic wars hannibal',
  'war-rome-civil': 'roman civil war',
  'war-crassus': 'battle of carrae crassus',
  'war-teutoburg': 'battle of teutoburg forest',
  'war-constantine': 'battle of milvian bridge',
  'war-hastings': 'battle of hastings 1066',
  'war-hattin': 'battle of hattin saladin',
  'war-mongol-west': 'mongol invasion europe',
  'war-crecy': 'battle of crecy hundred years',
  'war-constantinople': 'fall of constantinople 1453',
  'war-tours': 'battle of tours charles martel',
  'war-lepanto': 'battle of lepanto 1571',
  'war-thirty': 'thirty years war',
  'war-blenheim': 'battle of blenheim',
  'war-nordic': 'great northern war',
  'war-polish-swedish': 'deluge polish swedish',
  'war-austrian-spanish': 'war of spanish succession',
  'war-seven': 'seven years war',
  'war-napoleonic': 'napoleonic wars battle',
  'war-waterloo': 'battle of waterloo 1815',
  'war-crimean': 'crimean war',
  'war-french-prussian': 'franco prussian war',
  'war-boer': 'boer war south africa',
  'war-russo-japanese': 'russo japanese war',
  'war-balkan': 'balkan wars',
  'war-ww1': 'world war 1 trench',
  'war-ww2': 'world war 2 battlefield',
  'war-chinese-civil': 'chinese civil war',
  'war-korean': 'korean war',
  'war-vietnam': 'vietnam war',
  'war-sixday': 'six day war 1967',
  'war-yom-kippur': 'yom kippur war',
  'war-falklands': 'falklands war',
  'war-gulf': 'gulf war 1991',
  'war-iran-iraq': 'iran iraq war',
  'war-afghan': 'soviet afghan war',
  'war-iraq': 'iraq war 2003',
  'war-taiping': 'taiping rebellion china',
  'war-opium': 'opium war',
  'war-boxer': 'boxer rebellion china',
  'war-sino-japanese': 'second sino japanese war',
  'war-sengoku': 'sengoku period japan',
  'war-imjin': 'imjin war korea japan',
  'war-three-kingdoms': 'three kingdoms china',
  'war-red-cliff': 'battle of red cliffs',
  'war-an-shi': 'an shi rebellion tang',
  'war-nanzhao': 'nanzhao tang war',
  'war-jin-song': 'jin song wars china',
  'war-mongol-yuan': 'mongol conquest song',
  'war-qing-conquest': 'qing conquest ming',
  'war-chu-han': 'chu han contention',
  'war-seven-states': 'rebellion of seven states',
  'war-wang-mang': 'wang mang rebellion',
  'war-yellow-turban': 'yellow turban rebellion',
  'war-nan-bei': 'southern northern dynasties',
  'war-sui-chen': 'sui dynasty collapse',
  'war-roman-persian': 'roman persian wars',
  'war-islamic-conquest': 'islamic conquest persia',
  'war-crusades': 'crusades knights',
  'war-hussite': 'hussite wars',
  'war-100-years': 'hundred years war',
  'war-roses': 'wars of the roses',
  'war-holy-league': 'war of holy league',
  'war-italian-wars': 'italian wars renaissance',
  'war-ottoman-habsburg': 'ottoman habsburg wars',
  'war-mughal-maratha': 'mughal maratha wars',
  'war-aceh': 'aceh war dutch',
  'war-imperial-india': 'british conquest india',
  'war-taiping-final': 'taiping final stages',
  'war-asia-pacific': 'world war 2 pacific',
  'war-north-africa': 'north africa campaign',
  'war-eastern-front': 'eastern front ww2',
  'war-d-day': 'd day normandy',
  'war-cold-war': 'cold war berlin wall',
  'war-suez': 'suez crisis 1956',
  'war-bangladesh': 'bangladesh liberation war',
  'war-ogaden': 'ogaden war ethiopia',
  'war-western-sahara': 'western sahara conflict',
  'war-nagorno': 'nagorno karabakh',
  'war-balkans-90s': 'yugoslav wars',
  'war-chechnya': 'chechen wars',
  'war-isis': 'isis syria iraq',
  'war-ukraine': 'russia ukraine war',
  'war-xinhai': 'xinhai revolution china',
  'war-north-china': 'war of resistance china',
  'war-civil-war-africa': 'african civil wars',
}

/**
 * 文化事件 id -> 搜索关键词
 */
export const cultureSearchKeywords: Record<string, string> = {
  'ce-001': 'oracle bone script shang dynasty',
  'ce-002': 'hammurabi code stele',
  'ce-003': 'pyramid of giza egypt',
  'ce-004': 'acropolis athens parthenon',
  'ce-005': 'twelve tables roman law',
  'ce-006': 'sima qian historical records',
  'ce-007': 'cai lun paper invention',
  'ce-008': 'euclid elements manuscript',
  'ce-009': 'pantheon rome',
  'ce-010': 'great wall ming dynasty',
  'ce-011': 'block printing china',
  'ce-012': 'bi sheng movable type',
  'ce-013': 'lantingji xu calligraphy',
  'ce-014': 'dunhuang mogao caves',
  'ce-015': 'imperial examination china',
  'ce-016': 'compendium of materia medica',
  'ce-017': 'mona lisa painting',
  'ce-018': 'sistine chapel ceiling michelangelo',
  'ce-019': 'gutenberg bible',
  'ce-020': 'virgil aeneid manuscript',
  'ce-021': 'dante divine comedy manuscript',
  'ce-022': 'shakespeare first folio',
  'ce-023': 'luther 95 theses',
  'ce-024': 'newton principia mathematica',
  'ce-025': 'watt steam engine',
  'ce-026': 'declaration of rights of man',
  'ce-027': 'greek alphabet ancient',
  'ce-028': 'hammurabi code stone',
  'ce-029': 'gutenberg printing press',
  'ce-030': 'hinduism vedic',
  'ce-031': 'buddha bodh gaya',
  'ce-032': 'jesus christ holy land',
  'ce-033': 'quran manuscript',
  'ce-034': 'qin unification writing',
  'ce-035': 'twelve tables roman',
}

/**
 * 通用兜底：根据名字生成搜索词
 * - 中文名：直接用中文 + 类别后缀
 * - 英文名：原样
 */
export function fallbackKeyword(name: string, category?: string): string {
  if (!name) return 'history'
  // 中文名字 + 类别
  if (/[一-龥]/.test(name)) {
    if (category) return `${name} ${category}`
    return `${name} portrait`
  }
  // 英文
  return name
}

/**
 * 大型战争专题（MAJOR_WARS）的 key -> 搜索关键词
 * 与 WarsOverview.tsx 的 MAJOR_WARS 数组 key 一一对应
 */
export const majorWarSearchKeywords: Record<string, string> = {
  'ww1': 'world war 1 trenches',
  'ww2': 'world war 2 battlefield',
  'second-sino-japanese': 'second sino japanese war',
  'napoleonic': 'napoleonic wars battle painting',
  'mongol-conquest': 'mongol empire conquest',
  'thirty-years': 'thirty years war battle',
  'roman-civil': 'roman civil war ancient',
  'punic': 'punic war hannibal',
  'crusades': 'crusades knights jerusalem',
  'hundred-years': 'hundred years war crecy',
  'taiping': 'taiping rebellion china',
  'three-kingdoms': 'three kingdoms china red cliff',
  'warring-states': 'warring states period china',
  'chu-han': 'chu han contention china',
  'seven-kingdoms': 'rebellion of seven states china',
  'an-shi': 'an shi rebellion tang china',
  'imjin': 'imjin war korea',
  'sengoku': 'sengoku period japan samurai',
  'boxer': 'boxer rebellion china',
  'opium': 'opium war china',
  'roman-persian': 'roman persian wars',
  'islamic-conquest': 'islamic conquest persia',
  'xinhai': 'xinhai revolution china',
  'cold-war': 'cold war berlin wall',
  'korean': 'korean war',
  'vietnam': 'vietnam war jungle',
}
