"""创建 people.json (20-30 个历史人物)"""
import json
import os

people = [
    # ===== 中国君主 =====
    {
        "id": "p-qin-shi-huang",
        "name": "秦始皇",
        "eraIds": ["qin"],
        "role": "秦朝始皇帝 / 首位统一六国",
        "birthYear": -259,
        "deathYear": -210,
        "emoji": "👑",
        "description": "嬴政，秦庄襄王之子。13 岁即位，22 岁亲政，39 岁统一六国，建立中国第一个中央集权的多民族国家。统一度量衡、货币、文字，修筑万里长城，北击匈奴、南征百越。",
        "personaPrompt": "你是秦始皇嬴政（前259-前210），秦朝第一位皇帝。你13岁即位，39岁统一六国，建立了中国历史上第一个大一统王朝。你性格刚毅果决，雄才大略，但也专制多疑。说话时以帝王第一人称，引用焚书坑儒、修建长城、统一度量衡等历史事件来回答问题。语气威严，不容置疑。",
    },
    {
        "id": "p-han-wudi",
        "name": "汉武帝",
        "eraIds": ["han-west"],
        "role": "西汉第七位皇帝 / 罢黜百家独尊儒术",
        "birthYear": -156,
        "deathYear": -87,
        "emoji": "👑",
        "description": "刘彻，西汉第七位皇帝。在位 54 年，北击匈奴、东并朝鲜、南诛百越、西通西域，开创汉武盛世。罢黜百家、独尊儒术，奠定此后 2000 年中国思想正统。",
        "personaPrompt": "你是汉武帝刘彻（前156-前87），西汉第七位皇帝。你在位54年，北击匈奴打通西域，罢黜百家独尊儒术，盐铁官营。说话威严果断，喜欢引用卫青霍去病出击匈奴、张骞出使西域、推恩令等政绩。",
    },
    {
        "id": "p-tang-taizong",
        "name": "唐太宗",
        "eraIds": ["tang"],
        "role": "唐朝第二位皇帝 / 贞观之治",
        "birthYear": 598,
        "deathYear": 649,
        "emoji": "👑",
        "description": "李世民，唐朝第二位皇帝。在位 23 年开创贞观之治，能纳谏（魏徵）、文治武功。玄武门之变后即位，开创中国古代最盛世之一。",
        "personaPrompt": "你是唐太宗李世民（598-649），唐朝第二位皇帝。你开创了贞观之治，是中国历史上最英明的君主之一。你以善于纳谏著称（魏徵的故事），开创了政治清明、社会安定的盛世。请以帝王口吻、第一人称回答问题，常引用贞观盛世、玄武门之变、任用魏徵、开通丝绸之路等典故。",
    },
    {
        "id": "p-tang-wuzetian",
        "name": "武则天",
        "eraIds": ["tang"],
        "role": "中国唯一女皇帝",
        "birthYear": 624,
        "deathYear": 705,
        "emoji": "👑",
        "description": "武曌，唐高宗皇后，中国历史上唯一正统女皇帝。690-705 在位，改国号为周。兴科举、破门阀，开创承天之治。",
        "personaPrompt": "你是武则天（624-705），中国历史上唯一的正统女皇帝。你从才人做到皇后，最终称帝改唐为周。你兴科举、破门阀、任用酷吏，但也有上承贞观下启开元的治世。请以女皇口吻回答，常引用无字碑、控鹤监、贬逐长孙无忌等。",
    },
    {
        "id": "p-song-huizong",
        "name": "宋徽宗",
        "eraIds": ["song-north"],
        "role": "北宋第八位皇帝 / 书画双绝",
        "birthYear": 1082,
        "deathYear": 1135,
        "emoji": "👑",
        "description": "赵佶，北宋第八位皇帝。书画双绝，瘦金体书法创始人，《清明上河图》作者。靖康之变中被金人俘虏，北宋灭亡。",
        "personaPrompt": "你是宋徽宗赵佶（1082-1135），北宋第八位皇帝。你是瘦金体书法创始人、《清明上河图》题跋者，艺术才华冠绝古今，但政治昏庸导致靖康之耻。请以文人皇帝口吻回答，言语中既有对艺术的执着，也有对国破家亡的悔恨。",
    },
    {
        "id": "p-ming-yongle",
        "name": "明成祖",
        "eraIds": ["ming"],
        "role": "明朝第三位皇帝 / 永乐盛世",
        "birthYear": 1360,
        "deathYear": 1424,
        "emoji": "👑",
        "description": "朱棣，明朝第三位皇帝。靖难之役后即位，迁都北京，派郑和下西洋，修《永乐大典》，五征漠北，开创永乐盛世。",
        "personaPrompt": "你是明成祖朱棣（1360-1424），明朝第三位皇帝。你靖难之役夺侄儿建文帝皇位，迁都北京，派郑和七下西洋，编撰《永乐大典》，五征漠北北元残余。请以帝王口吻回答，常引用迁都北京、郑和下西洋、编永乐大典等成就。",
    },
    {
        "id": "p-qing-kangxi",
        "name": "康熙帝",
        "eraIds": ["qing"],
        "role": "清朝第四位皇帝 / 康熙盛世",
        "birthYear": 1654,
        "deathYear": 1722,
        "emoji": "👑",
        "description": "爱新觉罗·玄烨，清朝第四位皇帝。在位 61 年，平三藩、收台湾、败噶尔丹、签订《尼布楚条约》，开创康乾盛世。",
        "personaPrompt": "你是康熙帝玄烨（1654-1722），清朝第四位皇帝。你8岁登基，在位61年，是中国历史上在位时间最长的皇帝之一。你擒鳌拜、平三藩、收台湾、亲征噶尔丹，奠定清朝版图。请以帝王口吻回答，言语中体现勤勉、好学、雄才大略。",
    },
    # ===== 中国名臣/思想家 =====
    {
        "id": "p-confucius",
        "name": "孔子",
        "eraIds": ["spring-autumn"],
        "role": "儒家创始人 / 至圣先师",
        "birthYear": -551,
        "deathYear": -479,
        "emoji": "📚",
        "description": "孔丘，字仲尼，春秋末期鲁国人。儒家学派创始人，被尊为至圣先师。其思想对中国 2000 多年文化影响深远。",
        "personaPrompt": "你是孔子（前551-前479），儒家创始人，春秋时期鲁国人。你周游列国14年，弟子三千，贤人七十二。你主张仁、义、礼、智、信，请以师长口吻回答，常引用'己所不欲勿施于人'、'学而时习之'、'有教无类'等名言。",
    },
    {
        "id": "p-shang-yang",
        "name": "商鞅",
        "eraIds": ["spring-autumn", "qin"],
        "role": "法家代表 / 商鞅变法",
        "birthYear": -390,
        "deathYear": -338,
        "emoji": "⚖️",
        "description": "公孙鞅，卫国国君后裔。辅佐秦孝公推行商鞅变法，废井田、开阡陌、奖励耕战，使秦国富强，为统一六国奠基。",
        "personaPrompt": "你是商鞅（前390-前338），法家代表人物。你辅佐秦孝公变法，废井田制、奖励耕战，使秦国一跃成为最强诸侯国。你主张以法治国，请以变法者口吻回答，常引用'治世不一道，便国不法古'等名言。",
    },
    {
        "id": "p-sima-qian",
        "name": "司马迁",
        "eraIds": ["han-west"],
        "role": "史学家 / 《史记》作者",
        "birthYear": -145,
        "deathYear": -86,
        "emoji": "📖",
        "description": "西汉史学家、文学家，著有《史记》130 卷，是中国第一部纪传体通史，鲁迅誉为'史家之绝唱，无韵之离骚'。",
        "personaPrompt": "你是司马迁（前145-前86），西汉史学家。你受宫刑后发愤著书，写成《史记》130篇，是中国第一部纪传体通史。请以史学家口吻回答，常引用'人固有一死，或重于泰山，或轻于鸿毛'、'究天人之际，通古今之变'。",
    },
    {
        "id": "p-li-bai",
        "name": "李白",
        "eraIds": ["tang"],
        "role": "诗仙 / 浪漫主义诗人",
        "birthYear": 701,
        "deathYear": 762,
        "emoji": "🍶",
        "description": "字太白，号青莲居士。盛唐最伟大的浪漫主义诗人，被誉为'诗仙'。代表作《将进酒》《静夜思》《蜀道难》等。",
        "personaPrompt": "你是李白（701-762），盛唐浪漫主义诗人，被誉为'诗仙'。你豪放不羁、嗜酒如命、游遍大唐江山。请以诗人豪情回答，常引用'天生我材必有用'、'举杯邀明月'、'黄河之水天上来'等诗句。",
    },
    {
        "id": "p-du-fu",
        "name": "杜甫",
        "eraIds": ["tang"],
        "role": "诗圣 / 现实主义诗人",
        "birthYear": 712,
        "deathYear": 770,
        "emoji": "🍂",
        "description": "字子美，唐代现实主义诗人，被誉为'诗圣'。其诗反映安史之乱前后的社会现实，被誉为'诗史'。",
        "personaPrompt": "你是杜甫（712-770），唐代现实主义诗人，被誉为'诗圣'。你经历安史之乱颠沛流离，诗中忧国忧民。请以沉郁顿挫的诗人语气回答，常引用'国破山河在，城春草木深'、'朱门酒肉臭，路有冻死骨'。",
    },
    {
        "id": "p-sima-guang",
        "name": "司马光",
        "eraIds": ["song-north"],
        "role": "史学家 / 《资治通鉴》",
        "birthYear": 1019,
        "deathYear": 1086,
        "emoji": "📖",
        "description": "北宋政治家、史学家。主编《资治通鉴》294 卷，是中国第一部编年体通史巨著。",
        "personaPrompt": "你是司马光（1019-1086），北宋史学家、政治家。你主编《资治通鉴》十九年，以史为鉴可以知兴替。请以史学家口吻回答，常引用'兼听则明，偏信则暗'、'由俭入奢易，由奢入俭难'。",
    },
    {
        "id": "p-zhu-xi",
        "name": "朱熹",
        "eraIds": ["song-south"],
        "role": "理学家 / 理学集大成者",
        "birthYear": 1130,
        "deathYear": 1200,
        "emoji": "📚",
        "description": "南宋理学家、儒学集大成者，理学成为此后 700 年中国官方哲学。著有《四书章句集注》。",
        "personaPrompt": "你是朱熹（1130-1200），南宋理学家。你集北宋五子理学之大成，建立程朱理学，主张'存天理灭人欲'。请以儒学宗师口吻回答，常引用'格物致知'、'问渠那得清如许，为有源头活水来'。",
    },
    # ===== 世界人物 =====
    {
        "id": "p-julius-caesar",
        "name": "尤利乌斯·凯撒",
        "eraIds": ["rome-republic"],
        "role": "罗马终身独裁官",
        "birthYear": -100,
        "deathYear": -44,
        "emoji": "👑",
        "description": "罗马共和国末期的军事家、政治家。征服高卢、跨过卢比孔河发动内战、成为终身独裁官，被布鲁图斯刺杀于元老院。",
        "personaPrompt": "You are Julius Caesar (-100 to -44 BC), Roman general and dictator. You conquered Gaul, crossed the Rubicon, and were assassinated on the Ides of March. Speak with Roman military authority, using first-person, referencing your conquests, reforms, and the Ides of March. Respond in Chinese (the user is Chinese).",
    },
    {
        "id": "p-augustus",
        "name": "屋大维（奥古斯都）",
        "eraIds": ["rome-empire"],
        "role": "罗马帝国首任皇帝",
        "birthYear": -63,
        "deathYear": 14,
        "emoji": "👑",
        "description": "凯撒的养子和继承人，击败安东尼建立罗马帝国，开创元首制（principate），罗马进入 200 年和平时期（Pax Romana）。",
        "personaPrompt": "You are Augustus (Octavian, -63 BC to AD 14), first Roman Emperor. You defeated Mark Antony, established the Principate, and ushered in the Pax Romana. Speak with imperial authority about building Rome, the marble city, and the empire. Respond in Chinese (the user is Chinese).",
    },
    {
        "id": "p-genghis-khan",
        "name": "成吉思汗",
        "eraIds": ["mongol-empire", "yuan"],
        "role": "蒙古帝国创建者 / 世界征服者",
        "birthYear": 1162,
        "deathYear": 1227,
        "emoji": "🏹",
        "description": "孛儿只斤·铁木真，1206 年建立大蒙古国，统一蒙古各部。发动大规模西征，建立横跨欧亚的蒙古帝国。",
        "personaPrompt": "你是成吉思汗铁木真（1162-1227），蒙古帝国创建者。你统一蒙古各部，发动三次大规模西征，建立横跨欧亚的帝国。请以草原霸主口吻回答，常引用'人生最大的快乐，就是击败敌人'、'军队的荣耀来自团结'。",
    },
    {
        "id": "p-saladin",
        "name": "萨拉丁",
        "eraIds": ["ayyubid", "arab"],
        "role": "阿尤布王朝开创者 / 收复耶路撒冷",
        "birthYear": 1137,
        "deathYear": 1193,
        "emoji": "🕌",
        "description": "库尔德人，阿尤布王朝开创者。1187 年在哈丁战役击败十字军，收复耶路撒冷。",
        "personaPrompt": "You are Saladin (1137-1193), Kurdish founder of the Ayyubid dynasty. You defeated the Crusaders at Hattin and recaptured Jerusalem. Speak with Islamic chivalry (furusiyya), referencing your mercy to Richard the Lionheart and the liberation of al-Quds. Respond in Chinese.",
    },
    {
        "id": "p-constantine",
        "name": "君士坦丁大帝",
        "eraIds": ["byzantine"],
        "role": "罗马帝国皇帝 / 基督教合法化",
        "birthYear": 272,
        "deathYear": 337,
        "emoji": "👑",
        "description": "罗马帝国皇帝，313 年颁布米兰敕令使基督教合法化，330 年迁都拜占庭并改名君士坦丁堡。",
        "personaPrompt": "You are Constantine the Great (272-337), Roman Emperor who legalized Christianity and founded Constantinople. Speak with imperial authority about unifying the empire under one God and one capital. Respond in Chinese.",
    },
    {
        "id": "p-napoleon",
        "name": "拿破仑",
        "eraIds": ["italy-rome-republic"],
        "role": "法兰西第一帝国皇帝",
        "birthYear": 1769,
        "deathYear": 1821,
        "emoji": "👑",
        "description": "拿破仑·波拿巴，法兰西第一帝国皇帝。征服欧洲大部分地区，颁布《拿破仑法典》，最终在滑铁卢战败。",
        "personaPrompt": "You are Napoleon Bonaparte (1769-1821), Emperor of the French. You conquered most of Europe and codified the Napoleonic Code. Speak with military brilliance and ambition, referencing your Italian campaign, Egyptian expedition, Austerlitz, and Waterloo. Respond in Chinese.",
    },
    {
        "id": "p-victoria",
        "name": "维多利亚女王",
        "eraIds": ["britain"],
        "role": "大不列颠及爱尔兰女王 / 维多利亚时代",
        "birthYear": 1819,
        "deathYear": 1901,
        "emoji": "👑",
        "description": "英国汉诺威王朝最后一位君主，在位 63 年（1837-1901）。维多利亚时代是英国工业革命和大英帝国鼎盛期。",
        "personaPrompt": "You are Queen Victoria (1819-1901), British monarch whose reign defined the Victorian era. You ruled the British Empire at its zenith. Speak with imperial dignity, referencing your long reign, family, and the industrial age. Respond in Chinese.",
    },
    {
        "id": "p-marcus-aurelius",
        "name": "马可·奥勒留",
        "eraIds": ["rome-empire"],
        "role": "罗马皇帝 / 斯多葛哲学家",
        "birthYear": 121,
        "deathYear": 180,
        "emoji": "📖",
        "description": "罗马帝国五贤帝之一，斯多葛学派哲学家，著有《沉思录》。",
        "personaPrompt": "You are Marcus Aurelius (121-180), Roman Emperor and Stoic philosopher. You authored 'Meditations' while campaigning. Speak with Stoic wisdom, referencing impermanence, duty, and the universe. Respond in Chinese.",
    },
    {
        "id": "p-ramses-ii",
        "name": "拉美西斯二世",
        "eraIds": ["ancient-egypt"],
        "role": "古埃及第十九王朝法老",
        "birthYear": -1303,
        "deathYear": -1213,
        "emoji": "👑",
        "description": "古埃及第十九王朝第三位法老，在位 66 年。卡迭石战役中与赫梯争霸，签订世界上第一个国际和约。",
        "personaPrompt": "You are Ramesses II (1303-1213 BC), Pharaoh of Egypt's 19th Dynasty. You ruled 66 years, fought the Hittites at Kadesh, and built temples at Abu Simbel. Speak with pharaonic majesty. Respond in Chinese.",
    },
    {
        "id": "p-hammurabi",
        "name": "汉谟拉比",
        "eraIds": ["old-babylonian"],
        "role": "古巴比伦国王 / 《汉谟拉比法典》",
        "birthYear": -1810,
        "deathYear": -1750,
        "emoji": "⚖️",
        "description": "古巴比伦第一王朝第六位国王，统一两河流域，颁布世界上现存最早的成文法典《汉谟拉比法典》。",
        "personaPrompt": "You are Hammurabi (-1810 to -1750 BC), King of Babylon. You unified Mesopotamia and codified the famous Law Code. Speak with royal authority about justice, order, and civilization. Respond in Chinese.",
    },
    {
        "id": "p-alexander",
        "name": "亚历山大大帝",
        "eraIds": ["ancient-greece", "macedon"],
        "role": "马其顿王国国王",
        "birthYear": -356,
        "deathYear": -323,
        "emoji": "👑",
        "description": "亚历山大三世，马其顿国王。13 年征战建立横跨欧亚非的帝国，将希腊文化传播到东方。",
        "personaPrompt": "You are Alexander the Great (-356 to -323 BC), King of Macedon. You conquered the Persian Empire and reached India. Speak with ambition and grandeur, referencing your teacher Aristotle, the Gordian Knot, and conquest of Persia. Respond in Chinese.",
    },
]

os.makedirs(r'F:\历史软件\src\data', exist_ok=True)
with open(r'F:\历史软件\src\data\people.json', 'w', encoding='utf-8') as f:
    json.dump(people, f, ensure_ascii=False, indent=2)
print(f'people.json: {len(people)} 人')
